Repository eclipse-che4z/che-che4z-explorer-for-endevor, pull requests merged in 2023-11, with the labels that each got.

#344 Add combined test coverage report
  .eslintignore
  .prettierignore
  .prettierignore-ci
  combined_coverage_report.sh
  package.json
  packages/endevor/jest.config.js
  packages/explorer-for-endevor/jest.config.js
  packages/explorer-for-endevor/package.json
  packages/profiles/jest.config.js
  packages/type-parser/jest.config.js
  packages/views/jest.config.js
  yarn.lock
Labels: enhancement, Technical debt

#346 Mitigate vulnerabilities in the minor/patch transitive packages
  yarn.lock
Labels: dependencies

#345 Ask proc group for upload
  packages/endevor/__tests__/api-v1-test.ts
  packages/endevor/__tests__/api-v2-test.ts
  packages/endevor/_doc/Endevor.ts
  packages/endevor/endevor.ts
  packages/explorer-for-endevor/src/api/endevor.ts
  packages/explorer-for-endevor/src/commands/__tests__/_mocks/dialogs.ts
  packages/explorer-for-endevor/src/commands/__tests__/_mocks/endevor.ts
  packages/explorer-for-endevor/src/commands/__tests__/discardEditedElementChanges.test.ts
  packages/explorer-for-endevor/src/commands/__tests__/uploadElement.test.ts
  packages/explorer-for-endevor/src/commands/element/applyDiffEditorChanges.ts
  packages/explorer-for-endevor/src/commands/element/compareElementWithRemoteVersion.ts
  packages/explorer-for-endevor/src/commands/element/generateElementInPlace.ts
  packages/explorer-for-endevor/src/commands/element/generateElementWithCopyBack.ts
  packages/explorer-for-endevor/src/commands/element/uploadElement.ts
  packages/explorer-for-endevor/src/commands/location/addElementFromFileSystem.ts
  packages/explorer-for-endevor/src/dialogs/processor-groups/processorGroupsDialogs.ts
  packages/explorer-for-endevor/src/uri/_doc/Uri.ts
  packages/explorer-for-endevor/src/uri/comparedElementUri.ts
Labels: enhancement
